# # # Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# # target 'Project1' do
# #   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
# #   # use_frameworks!

# #   # Pods for Project1

# #   target 'Project1-tvOSTests' do
# #     inherit! :search_paths
# #     # Pods for testing
# #   end


# #     pod 'React', path: '../node_modules/react-native', :subspecs => [
# #       'Core',
# #       'RCTActionSheet',
# #       'RCTGeolocation',
# #       'RCTImage',
# #       'RCTLinkingIOS',
# #       'RCTNetwork',
# #       'RCTSettings',
# #       'RCTText',
# #       'RCTVibration',
# #       'RCTWebSocket'
# #     ]
  
# #     pod 'GoogleMaps'
# #   target 'Project1Tests' do
# #     inherit! :search_paths
# #     # Pods for testing
# #   end

# # end

# # target 'Project1-tvOS' do
# #   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
# #   # use_frameworks!

# #   # Pods for Project1-tvOS

# #   target 'Project1-tvOSTests' do
# #     inherit! :search_paths
# #     # Pods for testing
# #   end

# # end

# target 'Project1' do
# pod 'React', path: '../node_modules/react-native', :subspecs => [
#       'Core',
#       'RCTActionSheet',
#       'RCTGeolocation',
#       'RCTImage',
#       'RCTLinkingIOS',
#       'RCTNetwork',
#       'RCTSettings',
#       'RCTText',
#       'RCTVibration',
#       'RCTWebSocket'
#     ]
  
#     pod 'GoogleMaps'
#     pod 'react-native-google-maps', path: '../node_modules/react-native-maps'  # If you need GoogleMaps support on iOS
#     pod 'react-native-maps', path: '../node_modules/react-native-maps'


#   end




# You Podfile should look similar to this file. React Native currently does not support use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

# Change 'AirMapsExplorer' to match the target in your Xcode project.
target 'Project1' do
  rn_path = '../../node_modules/react-native' # This path is likely to be `../node_modules/react-native` in your own project.
  rn_maps_path = '../../' # This path is likely to be `../node_modules/react-native-maps` in your own project.

  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  # react-native-maps dependencies
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Remove this line if you don't want to support GoogleMaps on iOS
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
  end
end